### ISSUE TITLE
[BUG] Z offset doesn't work

### ISSUE THREAD

**Issue by Gavster30** [JGMaker3dofficial/artistd#59]
### Bug Description

I can babystep and found out the perfect level is -0.130, now I can't save babystepping for later or put in an offsett on the machine and save it. Bed Z doesn't make any difference to height at all.

### My Configurations

[Marlin.zip](https://github.com/JGMaker3dofficial/artistd/files/6284471/Marlin.zip)

### Steps to Reproduce

1. Navigate Motion -> Bed Levelling -> Bed Z:
2. Change the number up or down, it doesn't do anything
3. Store settings

**Expected behavior:**
I would expect the Z to move closer or further away when printing.

**Actual behavior:**
Nothing changes that I can see?

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by mikejr83** [comment]
I think this is an bug or incorrect assumption regarding the bed leveling system. We're using mesh bed leveling with out a probe. If you're used to a probe going around with `G29` to make a mesh of the bed that's a bit different. The offset that you're saving isn't really babystepping, but a probe offset. That's how I understand it. As far as I know there isn't a configuration for saving babystep offset. I'll have to look more into bed offset of some kind. One thing I can think of is that you can put in the offset to your slicer. You should also see if there is a octoprint plugin or something that will append that gcode so that you're not hard-coding it into a specific sliced file and can change it on the fly.
